component: payment-stage
service_type: ClusterIP
port: 80
container_port: 8080
target_port: 8080
PARAMETERS_ENABLED: true
PARAMETERS: "payment.stage.CART_HOST_k,CART_HOST payment.stage.CART_PORT_k,CART_PORT payment.stage.USER_HOST_k,USER_HOST payment.stage.USER_PORT_k,USER_PORT payment.stage.AMQP_HOST_k,AMQP_HOST payment.stage.AMQP_USER_k,AMQP_USER payment.stage.AMQP_PASS_k,AMQP_PASS"
env: stage

resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 800m
    memory: 1500Mi