name: Python application

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: workstation

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.6
      uses: actions/setup-python@v4
      with:
        python-version: "3.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
