name: Python application

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: workstation

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo python3.6 -m pip install --upgrade pip
