name: Python application

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: workstation
    steps:
    - uses: actions/checkout@v4
    - name: Test cases
      run: echo Test cases passed
      
  sonarqube-scan:
    needs: test
    runs-on: workstation
    steps:
    - uses: actions/checkout@v4
    
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5.1.0 # Ex: v4.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
      with:
        args: >
          -Dsonar.projectKey="payment"
          -Dsonar.exclusions=**/Dockerfile
          
    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      with:
        pollingTimeoutSec: 600
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}

  code-security:
    needs: sonarqube-scan
    runs-on: workstation
    steps:
    - uses: actions/checkout@v4

    - name: Code Security
      run: echo Code Security
