name: Python application

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: workstation

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        python3.6 -m pip3.6 install --upgrade pip
        pip3.6 install pytest
        if [ -f requirements.txt ]; then pip3.6 install -r requirements.txt; fi
